modify slack notification message

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -1,47 +1,44 @@
 steps:
-  - name: gcr.io/cloud-builders/docker
+  - name: 'gcr.io/cloud-builders/docker'
+    entrypoint: bash
     args:
-      - build
-      - '--no-cache'
-      - '-t'
-      - >-
-        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
-      - .
-      - '-f'
-      - dockerfile
+      - '-c'
+      - |
+        trap "echo 'FAILURE' > /workspace/build_status" EXIT
+        docker build --no-cache -t $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA . -f dockerfile
+        trap - EXIT
     id: Build
-  - name: gcr.io/cloud-builders/docker
+
+  - name: 'gcr.io/cloud-builders/docker'
+    entrypoint: bash
     args:
-      - push
-      - >-
-        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
+      - '-c'
+      - |
+        trap "echo 'FAILURE' > /workspace/build_status" EXIT
+        docker push $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
+        trap - EXIT
     id: Push
+
   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
+    entrypoint: bash
     args:
-      - run
-      - services
-      - update
-      - $_SERVICE_NAME
-      - '--platform=managed'
-      - >-
-        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
-      - >-
-        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
-      - '--region=$_DEPLOY_REGION'
-      - '--quiet'
+      - '-c'
+      - |
+        trap "echo 'FAILURE' > /workspace/build_status" EXIT
+        gcloud run services update $_SERVICE_NAME --platform=managed --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID --region=$_DEPLOY_REGION --quiet
+        trap - EXIT
     id: Deploy
-    entrypoint: gcloud
+
   - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: bash
     args:
       - '-c'
       - |
-        status=0 # Initialize status to success 
-        for i in {0..2}; do  # Check the status of the first 3 steps (Build, Push, Deploy)
-          if [ "${{ steps[${i}].status }}" != "SUCCESS" ]; then
-            status=1 # Mark as failure if any step failed
-          fi
-        done
+        if [ -f /workspace/build_status ] && grep -q 'FAILURE' /workspace/build_status; then
+          status=1
+        else
+          status=0
+        fi
         webhook_url=$(gcloud secrets versions access latest --secret=SLACK_WEBHOOK)
         chmod +x ./scripts/notify_slack.sh
         ./scripts/notify_slack.sh "$status" "$webhook_url" "${BUILD_ID}" "${PROJECT_ID}" "$_BRANCH_NAME" "$_ENVIRONMENT"
@@ -51,22 +48,24 @@ steps:
       - 'PROJECT_ID=$PROJECT_ID'
       - 'ENVIRONMENT=$_ENVIRONMENT'
       - 'BRANCH_NAME=$_BRANCH_NAME'
-    waitFor: 
-      - '-'
+
 images:
   - >-
     $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
+
 options:
   substitutionOption: ALLOW_LOOSE
   logging: CLOUD_LOGGING_ONLY
+
 substitutions:
   _DEPLOY_REGION: europe-north1
   _TRIGGER_ID: 81812211-73e8-41b8-85f2-55816362a5c2
   _AR_HOSTNAME: europe-north1-docker.pkg.dev
   _PLATFORM: managed
   _SERVICE_NAME: sb-ui-image
-  _ENVIRONMENT: production  # Default to production
-  _BRANCH_NAME: main        # Default to main 
+  _ENVIRONMENT: production
+  _BRANCH_NAME: main
+
 tags:
   - gcp-cloud-build-deploy-cloud-run
   - gcp-cloud-build-deploy-cloud-run-managed
